import { useState } from "react";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { trpc } from "@/lib/trpc";

type Line = { item: { id: number; name: string; price: string | number }; quantity: number };
export function CheckoutForm({ lines, onSuccess }: { lines: Line[]; onSuccess: () => void }) {
  const order = trpc.customer.placeOrder.useMutation();
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ name: "", phone: "", fulfillment: "pickup" as "pickup" | "delivery", payment: "pay_at_pickup" as "pay_at_pickup" | "cash_on_delivery", address: "", error: "", success: false });
  const subtotal = lines.reduce((sum, line) => sum + Number(line.item.price) * line.quantity, 0);
  function submit() {
    const phone = form.phone.replace(/[^0-9+]/g, "");
    if (form.name.trim().length < 2) return setForm({ ...form, error: "Please enter your full name." });
    if (!/^\+?[0-9]{10,13}$/.test(phone)) return setForm({ ...form, error: "Please enter a valid 10–13 digit phone number." });
    if (form.fulfillment === "delivery" && form.address.trim().length < 10) return setForm({ ...form, error: "Please enter your complete delivery address." });
    if (form.fulfillment === "delivery" && form.payment !== "cash_on_delivery") return setForm({ ...form, error: "Delivery orders use cash on delivery." });
    order.mutate({ customerName: form.name.trim(), customerPhone: phone, fulfillmentType: form.fulfillment, paymentMethod: form.payment, addressSnapshot: form.fulfillment === "delivery" ? form.address.trim() : undefined, items: lines.map(line => ({ menuItemId: line.item.id, nameSnapshot: line.item.name, priceSnapshot: String(line.item.price), quantity: line.quantity })) }, { onSuccess: () => setForm({ ...form, success: true, error: "" }), onError: error => setForm({ ...form, error: error.message || "We could not place that order. Please try again." }) });
  }
  if (!open) return <button onClick={() => setOpen(true)} className="mt-6 w-full rounded-full bg-[#251925] px-5 py-4 text-xs font-semibold uppercase tracking-[0.2em] text-white transition hover:bg-[#6e3d2d]">Continue to checkout <ArrowRight className="ml-2 inline" size={14}/></button>;
  return <div className="mt-6 rounded-2xl border border-[#251925]/15 bg-white/40 p-4"><p className="text-[10px] uppercase tracking-[0.2em] text-[#9b684c]">Checkout · ₹{subtotal.toFixed(0)}</p>{form.success ? <div className="py-6 text-center"><CheckCircle2 className="mx-auto text-[#4e7b56]" size={28}/><p className="mt-3 font-serif text-2xl">Order received.</p><p className="mt-2 text-sm text-[#6e3d2d]/70">The restaurant will confirm it by phone.</p><button onClick={() => { onSuccess(); setOpen(false); }} className="mt-5 rounded-full bg-[#251925] px-5 py-3 text-xs uppercase tracking-[0.18em] text-white">Done</button></div> : <div className="mt-4 grid gap-3"><label className="text-xs">Full name<input value={form.name} onChange={e => setForm({ ...form, name: e.target.value, error: "" })} className="mt-1 w-full rounded-xl border border-[#251925]/15 bg-transparent px-3 py-3"/></label><label className="text-xs">Phone number<input inputMode="tel" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value, error: "" })} className="mt-1 w-full rounded-xl border border-[#251925]/15 bg-transparent px-3 py-3"/></label><div className="grid grid-cols-2 gap-2"><select value={form.fulfillment} onChange={e => setForm({ ...form, fulfillment: e.target.value as "pickup" | "delivery", payment: e.target.value === "delivery" ? "cash_on_delivery" : "pay_at_pickup", error: "" })} className="rounded-xl border border-[#251925]/15 bg-transparent px-3 py-3 text-xs"><option value="pickup">Pickup</option><option value="delivery">Delivery</option></select><select value={form.payment} onChange={e => setForm({ ...form, payment: e.target.value as "pay_at_pickup" | "cash_on_delivery", error: "" })} className="rounded-xl border border-[#251925]/15 bg-transparent px-3 py-3 text-xs"><option value="pay_at_pickup">Pay at pickup</option><option value="cash_on_delivery">Cash on delivery</option></select></div>{form.fulfillment === "delivery" && <label className="text-xs">Delivery address<textarea value={form.address} onChange={e => setForm({ ...form, address: e.target.value, error: "" })} className="mt-1 min-h-20 w-full rounded-xl border border-[#251925]/15 bg-transparent px-3 py-3"/></label>}{form.error && <p className="text-xs text-[#b44d3d]">{form.error}</p>}<button disabled={order.isPending} onClick={submit} className="rounded-full bg-[#251925] px-5 py-4 text-xs font-semibold uppercase tracking-[0.18em] text-white disabled:opacity-50">{order.isPending ? "Sending order…" : "Place order"}</button></div>}</div>;
}
